# Generated by Django 5.1 on 2024-08-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='story',
        ),
        migrations.RemoveField(
            model_name='texture',
            name='object',
        ),
        migrations.RemoveField(
            model_name='threedobject',
            name='page',
        ),
    ]
